export const REGISTER_USER_START = Symbol('REGISTER_USER_START');
export const REGISTER_USER_SUCCESS = Symbol('REGISTER_USER_SUCCESS');
export const REGISTER_USER_FAILED = Symbol('REGISTER_USER_FAILED');

export const LOGIN_USER_START = Symbol('LOGIN_USER_START');
export const LOGIN_USER_SUCCESS = Symbol('LOGIN_USER_SUCCESS');
export const LOGIN_USER_FAILED = Symbol('LOGIN_USER_FAILED');
